In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.5'

In [4]:
np.random.randint(7,9)


7

In [5]:
np.random.randint(1,5,4)   #4 means it will generate random 4 int numbers

array([2, 2, 1, 1], dtype=int32)

In [6]:
np.random.randint(5,2,3)


ValueError: low >= high

In [7]:
np.random.randint(10,40,(10,10))

array([[31, 10, 38, 12, 31, 18, 22, 22, 19, 26],
       [10, 32, 20, 26, 30, 24, 27, 25, 18, 33],
       [21, 24, 31, 34, 30, 27, 37, 17, 15, 20],
       [17, 36, 19, 37, 28, 34, 33, 18, 10, 25],
       [29, 30, 32, 12, 37, 34, 36, 18, 35, 35],
       [10, 21, 27, 27, 25, 30, 11, 37, 19, 31],
       [21, 20, 22, 29, 29, 15, 25, 31, 32, 15],
       [12, 25, 13, 18, 28, 18, 36, 17, 39, 31],
       [25, 15, 16, 29, 31, 23, 25, 23, 24, 16],
       [26, 20, 28, 25, 35, 34, 23, 20, 33, 22]], dtype=int32)

In [9]:
ri = np.random.randint(10,40,(3,5))
ri

array([[13, 21, 24, 25, 27],
       [16, 32, 28, 13, 30],
       [37, 13, 28, 22, 24]], dtype=int32)

In [10]:
len(ri)   

3

In [12]:
ri.shape

(3, 5)

In [13]:
id(ri)

2465031625232

In [14]:
ri

array([[13, 21, 24, 25, 27],
       [16, 32, 28, 13, 30],
       [37, 13, 28, 22, 24]], dtype=int32)

# SLICING IN NUMPY

In [15]:
ri[:]

array([[13, 21, 24, 25, 27],
       [16, 32, 28, 13, 30],
       [37, 13, 28, 22, 24]], dtype=int32)

In [16]:
ri[1]

array([16, 32, 28, 13, 30], dtype=int32)

In [17]:
ri[0:3]

array([[13, 21, 24, 25, 27],
       [16, 32, 28, 13, 30],
       [37, 13, 28, 22, 24]], dtype=int32)

In [21]:
ri_1 =np.random.randint(10,40,(10,10))
print(ri_1)

[[12 16 11 20 34 31 36 26 38 32]
 [18 26 38 38 13 11 29 38 13 28]
 [13 19 18 11 17 34 23 31 20 37]
 [27 16 18 29 35 32 25 21 16 19]
 [29 16 34 23 38 34 10 35 35 37]
 [15 23 20 19 38 29 34 28 28 38]
 [24 15 15 21 10 35 32 14 20 38]
 [27 38 21 20 25 27 33 30 35 26]
 [36 24 13 33 20 19 18 14 33 31]
 [17 34 22 21 28 32 23 21 11 26]]


In [20]:
ri_1.shape

(10, 10)

In [22]:
ri_1[3:7]

array([[27, 16, 18, 29, 35, 32, 25, 21, 16, 19],
       [29, 16, 34, 23, 38, 34, 10, 35, 35, 37],
       [15, 23, 20, 19, 38, 29, 34, 28, 28, 38],
       [24, 15, 15, 21, 10, 35, 32, 14, 20, 38]], dtype=int32)

In [24]:
print(ri_1[3,8])

16


In [25]:
ri_1

array([[12, 16, 11, 20, 34, 31, 36, 26, 38, 32],
       [18, 26, 38, 38, 13, 11, 29, 38, 13, 28],
       [13, 19, 18, 11, 17, 34, 23, 31, 20, 37],
       [27, 16, 18, 29, 35, 32, 25, 21, 16, 19],
       [29, 16, 34, 23, 38, 34, 10, 35, 35, 37],
       [15, 23, 20, 19, 38, 29, 34, 28, 28, 38],
       [24, 15, 15, 21, 10, 35, 32, 14, 20, 38],
       [27, 38, 21, 20, 25, 27, 33, 30, 35, 26],
       [36, 24, 13, 33, 20, 19, 18, 14, 33, 31],
       [17, 34, 22, 21, 28, 32, 23, 21, 11, 26]], dtype=int32)

In [26]:
print(ri_1[-5])

[15 23 20 19 38 29 34 28 28 38]


In [27]:
print(ri_1[-5, -3])


28


In [28]:
print(ri_1[::3])


[[12 16 11 20 34 31 36 26 38 32]
 [27 16 18 29 35 32 25 21 16 19]
 [24 15 15 21 10 35 32 14 20 38]
 [17 34 22 21 28 32 23 21 11 26]]


In [29]:
print(ri_1[::-1])


[[17 34 22 21 28 32 23 21 11 26]
 [36 24 13 33 20 19 18 14 33 31]
 [27 38 21 20 25 27 33 30 35 26]
 [24 15 15 21 10 35 32 14 20 38]
 [15 23 20 19 38 29 34 28 28 38]
 [29 16 34 23 38 34 10 35 35 37]
 [27 16 18 29 35 32 25 21 16 19]
 [13 19 18 11 17 34 23 31 20 37]
 [18 26 38 38 13 11 29 38 13 28]
 [12 16 11 20 34 31 36 26 38 32]]


In [33]:
print(ri_1[::-5])


[[17 34 22 21 28 32 23 21 11 26]
 [29 16 34 23 38 34 10 35 35 37]]


In [34]:
ri_1

array([[12, 16, 11, 20, 34, 31, 36, 26, 38, 32],
       [18, 26, 38, 38, 13, 11, 29, 38, 13, 28],
       [13, 19, 18, 11, 17, 34, 23, 31, 20, 37],
       [27, 16, 18, 29, 35, 32, 25, 21, 16, 19],
       [29, 16, 34, 23, 38, 34, 10, 35, 35, 37],
       [15, 23, 20, 19, 38, 29, 34, 28, 28, 38],
       [24, 15, 15, 21, 10, 35, 32, 14, 20, 38],
       [27, 38, 21, 20, 25, 27, 33, 30, 35, 26],
       [36, 24, 13, 33, 20, 19, 18, 14, 33, 31],
       [17, 34, 22, 21, 28, 32, 23, 21, 11, 26]], dtype=int32)

In [32]:
ri_1[:,2]  #Prints the specific column

array([11, 38, 18, 18, 34, 20, 15, 21, 13, 22], dtype=int32)

In [36]:
print(ri_1 [2:6 , 5:8])

[[34 23 31]
 [32 25 21]
 [34 10 35]
 [29 34 28]]


In [37]:
print(ri_1 [0:3 , 0:3])

[[12 16 11]
 [18 26 38]
 [13 19 18]]


In [38]:
np.arange(1,13)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
np.arange(1,13).reshape(3,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# NUMPY MASKING OR FILTER

# Masking

In [41]:
mat = np.arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [43]:
mat.shape

(10, 10)

In [44]:
mat <50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [45]:

mat[mat<50 ]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [47]:
mat[mat<=50 ]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

# Python Code To Generate OTP

In [49]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 4212
