In [1]:
import numpy as np

In [4]:
np.__version__

'2.3.5'

In [ ]:
np.

In [5]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

In [7]:
arr = np.array(my_list) 
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr

array([0, 1, 2, 3, 4, 5])

In [11]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(10, 20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
np.arange(10, 20, 3) 

array([10, 13, 16, 19])

In [14]:
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(5, dtype=int) # 1d array 

array([0, 0, 0, 0, 0])

In [20]:
np.zeros((2,2)) #2d array 

array([[0., 0.],
       [0., 0.]])

In [21]:
np.zeros((2,2), dtype=int)

array([[0, 0],
       [0, 0]])

In [22]:
np.zeros((5,10), dtype=int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [23]:
np.ones(10) 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
np.ones((3,3), dtype = int) 

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [25]:
np.twos(3)

AttributeError: module 'numpy' has no attribute 'twos'

In [26]:
rand(4)

NameError: name 'rand' is not defined

In [27]:
random.rand(4)

NameError: name 'random' is not defined

In [35]:
np.random.rand(4) 

array([0.24599153, 0.24952216, 0.04902262, 0.88323716])

In [47]:
np.random.rand(2,2) 

array([[0.00426866, 0.84221029],
       [0.46119566, 0.75273114]])

In [55]:
np.random.randint(3) 

1

In [58]:
np.random.randint(10, 15)

10